# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\courseoop\inter2.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 419)
        self.SearchButton = QtWidgets.QPushButton(Dialog)
        self.SearchButton.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.SearchButton.setObjectName("SearchButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(130, 10, 331, 401))
        self.textEdit.setObjectName("textEdit")
        self.DeleteButton = QtWidgets.QPushButton(Dialog)
        self.DeleteButton.setGeometry(QtCore.QRect(10, 60, 111, 41))
        self.DeleteButton.setObjectName("DeleteButton")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(10, 370, 111, 41))
        self.ExitButton.setObjectName("ExitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dublicate Search 1.4 Release"))
        self.SearchButton.setText(_translate("Dialog", "Search"))
        self.DeleteButton.setText(_translate("Dialog", "Search&Delete"))
        self.ExitButton.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
